# Experiment 1: TensorFlow Installation & Version Check


In [1]:
pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


# Experiment 2: Creating and Printing Tensors


In [5]:
s=tf.constant(5)
print(s)

tf.Tensor(5, shape=(), dtype=int32)


In [6]:
v=tf.constant([1,2,3])
print(v)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
m=tf.constant([[1,2],[3,4]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
m3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(m3)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


Tensor Addition

In [11]:
a=tf.constant([10,20,30])
b=tf.constant([1,2,3])
d=tf.add(a,b)
print(d)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


# Experiment 3: Basic Tensor Operations

In [12]:
tensor1 = tf.constant([10, 20, 30])
tensor2 = tf.constant([5, 10, 15])

addition = tf.add(tensor1, tensor2)
subtraction = tf.subtract(tensor1, tensor2)
multiplication = tf.multiply(tensor1, tensor2)
division = tf.divide(tensor1, tensor2)

print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: tf.Tensor([15 30 45], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([ 5 10 15], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 50 200 450], shape=(3,), dtype=int32)
Division: tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


# Experiment 4: Data Types and Shape of Tensors

In [13]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

print("\nTensor:")
print(tensor)

print("Data Type:", tensor.dtype)
print("Shape:", tensor.shape)
print("Number of Dimensions:", tensor.ndim)


Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: 2


# Experiment 5: Converting NumPy Arrays to Tensors

In [15]:
import numpy as np

In [16]:
numpy_array = np.array([1, 2, 3, 4, 5])
tf_tensor = tf.convert_to_tensor(numpy_array)

print("\nNumPy Array:")
print(numpy_array)

print("\nConverted TensorFlow Tensor:")
print(tf_tensor)


NumPy Array:
[1 2 3 4 5]

Converted TensorFlow Tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
